TOLsys/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path as url
from tolsys import views as tolsys_views
from tolsys import urls as tolsys_urls
from django.conf.urls import include

urlpatterns = [
    url(r'^$', tolsys_views.MainPage, name='mainpage'),
    url(r'^tolsys/', include(tolsys_urls)),
    # url(r'^tolsys/', include(tolsys_urls)),
    url('admin/', admin.site.urls),
]

tolsys/urls.py
from django.contrib import admin
from django.urls import path
from tolsys import views
from django.urls import re_path as url

urlpatterns = [
    url(r'^newlist_url$', views.NewList, name='newlist'),
    url(r'^(\d+)/$', views.ViewList, name='viewlist'),
    url(r'^(\d+)/addans$', views.AddAns, name='addans'),
    url(r'^(\d+)/addappointment$', views.AddAppointment, name='addappointment'),
    url(r'^(\d+)/app_url$', views.App, name='app_url'),
    url(r'^edit/(\d+)', views.edit, name='edit'),
    url(r'^edit/update/(\d+)', views.update, name='update'),
    url(r'^(\d+)/delete/', views.delete, name='delete'),
    url(r'^None/Addans2/', views.Addans2, name='Addans2'),
    # path('app_url', views.App, name='app_url'),
    # path('', views.Summary)
    # path('addappointment', views.AddAppointment, name='addappointment'),
    path('topic', views.TopicPage, name='topic'),
    path('newsroom', views.Newsroom, name='newsroom'),
    path('findhelp', views.Findhelp, name='findhelp'),
    path('aboutus', views.Aboutus, name='aboutus'),
    # url(r'^(\d+)/delete$', views.Delete, name='delete'),
]

tolsys/models.py
from django.db import models

class Patient(models.Model):
	fname = models.CharField(max_length=200)
	mname = models.CharField(max_length=200)
	sname = models.CharField(max_length=200)
	bday = models.CharField(max_length=200)
	age = models.IntegerField(default=None, blank=False)
	sex = models.CharField(max_length=200)
	add = models.CharField(max_length=200)
	eml = models.CharField(max_length=200)
	mbl = models.IntegerField(default=None, blank=False)

class Survey(models.Model):
	patientid = models.ForeignKey(Patient,default=None, on_delete=models.CASCADE)
	dttoday = models.DateField(default=None, blank=False)
	sncwhen = models.TextField(default=None, blank=False)
	md = models.TextField(default=None, blank=False)
	cs = models.TextField(default=None, blank=False)
	dcd = models.TextField(default=None, blank=False)

	class meta:
		db_table = 'survey'
		verbose_name = 'survey'

class Appointment(models.Model):
	patientid = models.ForeignKey(Patient,default="None", on_delete=models.CASCADE)
	kdsession = models.TextField(default=None, blank=False)
	tpsession = models.TextField(default=None, blank=False)
	adate = models.TextField(default=None, blank=False)
	atime = models.TextField(default=None, blank=False)
	class meta:
		db_table = 'appointment'
		verbose_name = 'appointment'

tolsys/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from tolsys.models import Patient,Survey,Appointment

def MainPage(request):
	patientlist = Patient.objects.all()
	return render(request,'mainpage.html')

def ViewList(request,patientId):
	newPatient = Patient.objects.get(id=patientId)
	#patientlist = Survey.objects.filter(patientid=patientId)
	#return render(request,'surveypage.html',{'patientid':patientId,'patientList':patientlist})
	return render(request,'surveypage.html',{'newPatient':newPatient})

def NewList(request):
	vfname = request.POST['firstname']
	vmname = request.POST['middlename']
	vsname = request.POST['surname']
	vbday = request.POST['birthday']
	vage = request.POST['age']
	vsex = request.POST['sex']
	vadd = request.POST['address']
	veml = request.POST['email']
	vmbl = request.POST['mobile']
	newPatient =  Patient.objects.create(fname=vfname,mname=vmname,sname=vsname,
		bday=vbday,age=vage,sex=vsex,
		add=vadd,eml=veml,mbl=vmbl)
	# return redirect(f'/tolsys/viewlist_url')
	return redirect(f'/tolsys/{newPatient.id}/')

def AddAns(request, patientId):
	newPatient = Patient.objects.get(id=patientId)
	vdttoday = request.POST['dttoday']
	vsncwhen = request.POST['sncwhen']
	vmd = request.POST['md']
	vcs = request.POST['cs']
	vdcd = request.POST['dcd']
	Survey.objects.create(patientid=newPatient,dttoday=vdttoday,sncwhen=vsncwhen,md=vmd,cs=vcs,dcd=vdcd)
	return redirect(f'/tolsys/{newPatient.id}/')
	# return redirect(f'/tolsys/{vpatientid.id}/')

def delete(request, patientId):
	newPatient =  Patient.objects.get(id=patientId)
	newPatient.delete()
	return redirect(f'/tolsys/{None}/Addans2/')

def Addans2(request):
	return render(request, 'surveypage.html')

def edit(request, patientId):
	newPatient = Patient.objects.get(id=patientId)
	survey = Survey.objects.filter(id=patientId)
	print (survey)
	# vdttoday = request.POST['datetoday']
	# vsncwhen = request.POST['sincewhen']
	# vmd = request.POST['mood']
	# vcs = request.POST['cause']
	# vdcd = request.POST['decide']
	# Survey.objects.create(patientid=newPatient,dttoday=vdttoday,sncwhen=vsncwhen,md=vmd,cs=vcs,dcd=vdcd)
	return render(request,'edit.html', {'survey':survey,'newPatient':newPatient})

def update(request, patientId):
	newPatient = Patient.objects.get(id=patientId)
	survey = Survey.objects.get(id=patientId)
	survey.dttoday = request.POST['dttoday']
	survey.sncwhen = request.POST['sncwhen']
	survey.md = request.POST['md']
	survey.cs = request.POST['cs']
	survey.dcd = request.POST['dcd']
	survey.save()
	return redirect(f'/tolsys/{survey.id}/addans/')
	# return render(request,'surveypage.html',{'newPatient':newPatient})

# def edit(request, rId):
# 	cuiReg = Registration.objects.get(id=rId)
# 	cuisineClass = CookingClass.objects.filter(regid=rId)
# 	print (cuisineClass)
# 	schedClass = Schedule.objects.filter(regid=rId)
# 	print (schedClass)
# 	checkoutMod = CheckoutInfo.objects.filter(regid=rId)
# 	print (schedClass)
# 	return render(request,'edit.html', {'cuiReg':cuiReg, 'cuisineClass':cuisineClass, 
# 		'schedClass':schedClass, 'checkoutMod':checkoutMod})


def AddAppointment(request, patientId):
	newPatient =  Patient.objects.get(id=patientId)
	return render(request, 'appointment.html', {'appointment': newPatient})

# def App(request):
# 	vkdsession = request.POST['kind']
# 	vtpsession = request.POST['type']
# 	vadate = request.POST['adate']
# 	vatime = request.POST['atime']
# 	Appointment.objects.create(kdsession=vkdsession,tpsession=vtpsession,adate=vadate,atime=vatime)
# 	return render(request, 'appsummary.html')

# def Delete(request, patientId):
# 	newPatient = Patient.objects.get(id=patientId)
# 	newPatient.delete()
# 	return redirect(f'/tolsys/{newPatient.id}/')

def App(request, patientIdd):
	pPatient = Patient.objects.get(id=patientIdd)
	patientid = request.POST.get('patientIdd','')
	vkdsession = request.POST['kind']
	vtpsession = request.POST['type']
	vadate = request.POST['adate']
	vatime = request.POST['atime']
	Appointment.objects.create(patientid=pPatient,kdsession=vkdsession,tpsession=vtpsession,adate=vadate,atime=vatime)
	# return render(request, 'appsummary.html', {'appointment': newPatient})
	return redirect(f'/tolsys/{pPatient.id}/')

# def App(request, patientId):
# 	newPatient = Patient.objects.get(id=patientId)
# 	newPatient = patientId()
# 	if request.method=='POST':
# 		Appointment.objects.create(patientid=newPatient,kdsession = request.POST['kind'],
# 			tpsession = request.POST['type'],adate = request.POST['adate'],atime = request.POST['atime'])
# 		return redirect(f'/tolsys/{newPatient.id}/')
# 	else:
# 		return render(request, 'appsummary.html', {'newPatient': newPatient})

# def Summary(request):
# 	patientdisplay=Patient.objects.all()
# 	appointmentdisplay=Appointment.all()
# 	return render(request,'appsummary.html',{'Patient':patientdisplay,'Appointment':appointmentdisplay})

# def AddAppointment(request, patientId):
# 	newPatient =  Patient.objects.get(id=patientId)
# 	apppointment = Appointment.objects.all()
# 	return render(request, 'appointment/apppointment.html',
# 		{'appointment': apppointment}, {'appointment': newPatient})

# def Summary(request):
# 	# newPatient = Patient.objects.get(id=patientId)
# 	vkdsession = request.POST['kind']
# 	vtpsession = request.POST['type']
# 	vadate = request.POST['adate']
# 	vatime = request.POST['atime']
# 	Appointment.objects.create(kdsession=vkdsession,tpsession=vtpsession,adate=vadate,atime=vatime)
# 	return redirect(f'/tolsys/{newPatient.id}/')




# def Appointment(request, patientId):
# 	newPatient = Patient.objects.get(id=patientId)
# 	if request.method=='POST':
# 		Appointment.objects.create(patientid=newPatient,
# 	kdsession = request.POST['kind'],
# 	tpsession = request.POST['type'],
# 	adate = request.POST['adate'],
# 	atime = request.POST['atime'],)
# 	# return redirect(f'/tolsys/viewlist_url')
# 	return render(request, 'appsummary.html', {'appointment': newPatient})



#From WebDev 1
def TopicPage(request):
	return render(request,'Topics.html')

def Newsroom(request):
	return render(request,'Newsroom.html')

def Findhelp(request):
	return render(request,'FindHelp.html')

def Aboutus(request):
	return render(request,'AboutUs.html')

	

tolsys/templates/AboutUs.html
{% extends 'template.html' %}
{% block title %} Tinkle Out Loud {% endblock %}
{% block h3_text %} Consultation and Counseling Appointment (CACATOL) {% endblock %}
{% block form_table_div %}
{% load static %}

    <script src="https://smtpjs.com/v3/smtp.js"></script>
	<script type="text/javascript">function sendMail() {
  		var sender=Form.sender.value;
		var password=Form.password.value;
		var receiver=Form.reciever.value;
		var content=Form.content.value;

		Email.send({
			Host: "smtp.gmail.com",
			Username: sender,
			Password:password,
			To: receiver,
			From: sender,
			Subject: "Check Email Sending",
			Body: content,

  		}).then(function (message) {
		alert("Email sent successfully")
		});
		}

		function myFunction(rate) {
  		document.getElementById("content").value = rate;
		}
	</script>

<body class="aboutbg">	
	<div class="aboutcolumn">
		<h2 class="abouth1">Values</h2>
			<p class="aboutp">Women, YOU can do better! It's time to act, it's time to fight. Happiness is everyone's right.</p>
	</div>

	<div class="aboutcolumn">
		<h2 class="abouth1">Mission</h2>
			<p class="aboutp">To offer encouragement and hope.  To support healing and recovery and say yes to freedom.</p>
	</div>

	<div class="aboutcolumn">
		<h2 class="abouth1">Vision</h2>
			<p class="aboutp">To ensure acceptance and empowerment with every step we take together.</p>
	</div>

		<img class="logo" src="{% static 'img/logopic.svg' %}" alt="logo here."/>

		<div>
			<p class="tag"><a class="trefterm" href="DefinitionOfTermsLinkAboutUs.html">Terms </a>| <a class="trefterm" href="References.html">References </a>| Hoping that you hear that clear ringing sound. Take a break buddies. Thinkle Out Loud. </p>
			<center>
			<a href="mailto:blogher.tinkleoutloud@gmail.com?subject=Feedback&body=Message" target="blank">
				<img class="aboutimg" src="{% static 'img/fgmail.svg' %}" alt="Gmail logo here."/></a>
			<a href="https://www.facebook.com/BlogHer-TOL-111153451344381" target="blank">
				<img class="aboutimg" src="{% static 'img/fb.svg' %}" alt="Facebook logo here."/></a>
			<a href="https://instagram.com/bloghertol?utm_medium=copy_link" target="blank">
				<img class="aboutimg" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Instagram-Icon.png/1200px-Instagram-Icon.png" alt="Instagram logo here."/></a>
			<a href="https://twitter.com/bloghertol?t=2OaWXGQx4uuFSlXK6HwaCQ&s=07" target="blank">
				<img class="aboutimg" src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Twitter-logo.svg/2491px-Twitter-logo.svg.png" alt="Twitter logo here."/></a>
			</center>
		</div>
{% endblock %}

tolsys/templates/FindHelp.html
{% extends 'template.html' %}
{% block title %} Tinkle Out Loud {% endblock %}
{% block h3_text %} Consultation and Counseling Appointment (CACATOL) {% endblock %}
{% block form_table_div %}
{% load static %}
	<script>
		function list1(){
			document.getElementById('countries').innerHTML = '<p><b>Egypt:</b> +20 7622381; 7621602; 7621603</p><p><b>Ghana:</b> 2332 444 71279 / 233 244 846 701</p><p><b>Kenya:</b> +254 722 178 177 / 020 2051323</p><p><b>Mauritius:</b> 800 93 93 / +230 5 483 7233 (Whats App)/ 112</p><p><b>Nigeria:</b> 0700-THE-JOY-HUB (0700-843-569-482)</p>';
		}
		function list2(){
  			document.getElementById('countries').innerHTML = '<p><b>China:</b> 0800-810-1117 / 010-8295-1332 / 400 821 1215 / 273 9595</p><p><b>Hong Kong:</b> 2382 0000 / 2389 2222 / 2896 0000</p><p><b>India:</b> +918376804102 / +91-9820466726</p><p><b>Indonesia:</b> 500-454</p><p><b>Iran:</b> 00989127181037</p><p><b>Israel:</b> Hotline: 1201 / 972-9-8891333 / 972-76-8844400</p><p><b>Japan:</b> +81 (0) 3 5286 9090 / +81 (0) 6 4395 4343 </p><p><b>Jordan:</b>  0096 262 508 900 / 110</p><p><b>Kuwait:</b> 112</p><p><b>Mongolia:</b> (+976) 1800-2000</p><p><b>Russia:</b> 007 (8202) 577-577 / (7) 0942 224 621</p><p><b>Saudi Arabia:</b> 920 03 33 60</p><p><b>Singapore:</b> 1800- 221 4444 / 6389 2222</p><p><b>South Korea:</b> Counsel24: 1566-2525</p><p><b>Taiwan:</b> 0800 788 995 OR 1995</p><p><b>Turkey:</b> 0850 455 00 70 / 182</p><p><b>United Arab Emirates:</b> 800 46342 / 999</p><p><b>Vietnam:</b> 113</p>';
		}
		function list3(){
			document.getElementById('countries').innerHTML = '<p><b>Australia:</b> 13 11 14 / 03 63 31 3355</p><p><b>Fiji:</b> (0679) 670565</p><p><b>Guam:</b> (671) 647-8833 / 647-8834</p><p><b>New Zealand:</b> 0800 543 354</p><p><b>Papua New Guinea:</b> 675 326 0011</p><p><b>Tonga:</b> 23000 / 25144</p><p><b>Samoa:</b> (+381) 21-6623-393</p>';
		}
		function list4(){
  			document.getElementById('countries').innerHTML = '<p><b>Belgium:</b> 106 / 107</p><p><b>Germany:</b> 0800 1110 111 / 0800 1110 222</p><p><b>North Macedonia:</b> 02 2465 316</p><p><b>Romania:</b> 0800 801 200</p><p><b>Spain:</b> 717 003 717</p><p><b>Sweden:</b> 90101</p><p><b>Switzerland:</b> 143</p><p><b>Ukraine:</b> 0487 327715 / 0482 226565</p><p><b>United Kingdom:</b> 116123 / +44 (0) 8457 90 90 90 (UK - local rate)</p>';
		}
		function list5(){
			document.getElementById('countries').innerHTML = '<p><b>Alberta:</b> 1-800-565-3801</p><p><b>British Columbia:</b> 1-888-562-12144</p><p><b>Canada:</b> 1.833.456.4566 (Hotline) / 45645 (Text)</p><p><b>Costa Rica:</b> 506-253-5439</p><p><b>Cuba:</b> 532 348 14 49</p><p><b>Dominican Republic:</b>  1-800-273-8255 or call 911</p><p><b>El Salvador:</b>  911</p><p><b>Haiti:</b> 1-800-273-8255 or call 114</p><p><b>Jamaica:</b> 1-888-429-5273</p><p><b>Manitoba:</b> 1-888-322-3019</p><p><b>Mexico:</b> 525-510-2550 / 453777 / 018004727835</p><p><b>Nicaragua:</b> 505-268-6171</p>';
		}
		function list6(){
  			document.getElementById('countries').innerHTML = '<p><b>Argentina:</b> (011) 5275-1135</p><p><b>Bolivia:</b> (00 591 4) 4 25 42 42</p><p><b>Brazil:</b> 55 11 31514109</p><p><b>Chile:</b> (00 56 42) 22 12 00</p><p><b>Colombia:</b> (00 57 4) 448 2945</p><p><b>Ecuador:</b> (593) 2 6000477 / (593) 2 2923327</p><p><b>Honduras:</b> 9978-2335 – 9992-1002</p><p><b>Peru:</b> (00 51 1) 273 8026.</p><p><b>Venezuala:</b> 0241-8433308</p><p><b>Trinidad:</b> (868) 645 2800 / 645 6616</p>';
		}
	</script>
	<div class="notefh">
		<h3>If you’re feeling suicidal…</h3>
		<p>Problems don’t seem temporary—they seem overwhelming and permanent. But if you reach out for help, you will feel better. Even when life seems bleak and hopeless, know that you are not alone.</p>
	</div>
	<div class="tooltip">
		<h3>PHILIPPINE NATIONAL MENTAL HEALTH CRISIS HOTLINE</h3>
			<p>0966 351 4518 / 0917 899 8727 (Globe /Tm)</p>
			<p>0966 351 4518 (Smart / Sun / TNT)</p>
			<span class="tooltiptext">Please contact the hotlines, do not hesitate.</span>
	</div>

	<br>
	<center>
	<div>
		<label for="age"><b>Other Countries: </b></label>
		<br>
		<br>
		<input type="radio" onclick="list1()" name="hl"><b>Africa</b>
		<input type="radio"  onclick="list2()" name="hl"><b>Asia</b>
		<input type="radio" onclick="list3()" name="hl"><b>Australia & Oceana</b>
		<input type="radio"  onclick="list4()" name="hl"><b>Europe</b>
		<input type="radio" onclick="list5()" name="hl"><b>North America</b>
		<input type="radio"  onclick="list6()" name="hl"><b>South America</b>
	</div>
	<br>

	<div class="searchfield">
			<p class="choosep" id="countries">Please choose above.</p>
	</div>
	</center>

	<center>
		<p class="quote"><em>“In times of pain, when the future is too terrifying to contemplate and the past too painful to remember, I have learned to pay attention to right now. The precise moment I was in was always the only safe place for me.” -Julia Cameron</em></p>
	</center>

{% endblock %}

tolsys/templates/Newsroom.html
{% extends 'template.html' %}
{% block title %} Tinkle Out Loud {% endblock %}
{% block h3_text %} Consultation and Counseling Appointment (CACATOL) {% endblock %}
{% block form_table_div %}
{% load static %}

	<h2 class="newsh2">News | Articles | Videos</h2>

	<div class="newscolumn">
		<figure>
			<a class="newsa" href="https://www.economist.com/graphic-detail/2021/10/11/covid-19-has-led-to-a-sharp-increase-in-depression-and-anxiety " target="_blank">
				<img class="newsimg" src="https://infographics.economist.com/2021/20211009_WOC978/20211009_WOC978-Artboard_1_copy.png" alt="Image here." />
					<figcaption class="newsfigc">Covid-19 has led to a sharp increase in depression and anxiety</figcaption></a>
		</figure>

		<figure>
			<a class="newsa" href="https://www.psychiatryadvisor.com/home/topics/general-psychiatry/in-pandemic-health-related-socioeconomic-risks-related-to-mental-health-problems/" target="_blank">
				<img class="newsimg" src="https://www.psychiatryadvisor.com/wp-content/uploads/sites/8/2019/06/Sad-Woman_G_962279972.jpg" alt="Image here." />
					<figcaption class="newsfigc">Women’s Socioeconomic Shortfalls Linked to Depression, Anxiety During COVID-19 Pandemic</figcaption></a>
		</figure>
	</div>

	<div class="newscolumn">
		<figure>
			<a class="newsa" href="https://www.healthline.com/health/female-enhancement-pills" target="_blank">
				<img class="newsimg" src="https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/02/mirror-beauty-skin-732x549-thumbnail-732x549.jpg?w=630" alt="Image here." />
					<figcaption class="newsfigc">Female Enhancement Pills: Everything You Need to Know</figcaption></a>
		</figure>

		<figure>
			<a class="newsa" href="https://www.forbes.com/sites/alicebroster/2021/05/08/young-women-most-likely-to-feel-depressed-during-coronavirus-new-study-suggests/?sh=7187af8d183a" target="_blank">
				<img class="newsimg" src="https://imageio.forbes.com/specials-images/imageserve/60946dd471e32a9a6ded5a8d/Young-woman-upset/960x0.jpg?format=jpg&width=960" alt="Image here." />
					<figcaption class="newsfigc">Young Women Most Likely To Feel Depressed During Coronavirus, New Study Suggests</figcaption></a>
		</figure>
	</div>

	<div class="newscolumn">
		<figure>
			<a class="newsa" href="https://www.npr.org/sections/health-shots/2018/11/22/669960524/how-i-learned-to-talk-to-my-filipino-mom-about-my-mental-health" target="_blank">
				<img class="newsimg" src="https://media.npr.org/assets/img/2018/11/21/malaka-and-mom_custom-2bfe56292111a0b601bb41152c6ea446c264c93b-s300-c85.webp" alt="Image here." />
					<figcaption class="newsfigc">How I Learned To Talk To My Filipino Mom About My Mental Health</figcaption></a>
		</figure>

		<figure>
			<a class="newsa" href="https://www.msf.org/philippines-%E2%80%9Cdepression-can-be-much-disability-blindness%E2%80%9D" target="_blank">
				<img class="newsimg" src="https://www.msf.org/sites/default/files/styles/image_desktop/public/images/MSB2792.jpg?itok=lRnzN9Gg" alt="Image here." />
					<figcaption class="newsfigc">Depression can be as much of a disability as blindness</figcaption></a>
		</figure>
	</div>

	<div class="newscolumn">
 		<iframe class="newsiframe" src="https://www.youtube.com/embed/2OfevE8J43c" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
 		<iframe class="newsiframe" src="https://www.youtube.com/embed/a1Y1ocyudjs" title="YouTube video player" frameborder="00" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	</div>
{% endblock %}

tolsys/templates/edit.html
{% extends 'template.html' %}
{% block title %} Tinkle Out Loud {% endblock %}
{% block h3_text %} Consultation and Counseling Appointment (CACATOL) {% endblock %}
{% block form_table_div %}
{% load static %}

	<form method="POST" action="/tolsys/edit/update/{{ newPatient.id }}">
		{% csrf_token %}
		<fieldset class="surfset">
		<br>
		<label for="dttoday">Date Today:</label>
		{% for item in newPatient.survey_set.all %}
		<input type="date" id="dttoday" name="dttoday" placeholder="mm / dd / yyyy" value="{{item.dttoday}}" required >
		<br><br>
		<label for="sncwhen">Since when have you been experiencing depression? </label>
		<input type="date" id="sncwhen" size="25" name="sncwhen" placeholder="mm / dd / yyyy or yyyy only" value="{{item.sncwhen}}" required> 
		<br><br>
		<label for="md">How is your mood right now? </label>
		<input type="text" id="md" size="25" name="md" placeholder="Please type here." value="{{item.md}}" required>
		<br><br>
		<label for="cs">Is there sudden event in your life that causes you to have that kind of mood? </label>
		<input type="text" id="cs" size="25" name="cs" placeholder="Please type your experience here." value="{{item.cs}}" required>
		<br><br>
		<label for="dcd">What made you decide to find immediate support? </label>
		<input type="text" id="dcd" size="25" name="dcd" placeholder="Please type your experience here." value="{{item.dcd}}" required>
		<!-- <input class="surbutton" id="btnSubmit" type="submit" value="Submit" name="submit"> -->
		<button type="submit">Update</button>
		{% endfor %}
		<br>
		</fieldset>
	</form>
{% endblock %}

tolsys/templates/surveypage.html
{% extends 'template.html' %}
{% block title %} Tinkle Out Loud {% endblock %}
{% block h3_text %} Consultation and Counseling Appointment (CACATOL) {% endblock %}
{% block form_table_div %}
{% load static %}
<table>
	<tr>
		<td class>Patient Name: </td>
		<td class="surspace">Sex: </td>
		<td class="surspace">Age: </td>
	</tr>
	<tr>
		<td class>{{newPatient.fname.upper}} {{newPatient.mname.upper}} {{newPatient.sname.upper}}</td>
		<td class="surspace">{{newPatient.sex}}</td>
		<td class="surspace">{{newPatient.age}}</td>
	</tr>
</table>
		<form method="POST" action="/tolsys/{{newPatient.id}}/addans">
		{% csrf_token %}
		<p>Good day {{newPatient.fname.upper}}! Feel free to express yourself. Please answer this short interview of CACATOL.</p>
		<fieldset class="surfset">
		<br>
		<label for="dttoday">Date Today:</label>
		<input type="date" id="dttoday" name="dttoday" placeholder="mm / dd / yyyy" required>
		<br><br>
		<label for="sncwhen">Since when have you been experiencing depression? </label>
		<input type="date" id="sncwhen" size="25" name="sncwhen" placeholder="mm / dd / yyyy or yyyy only" required>
		<br><br>
		<label for="md">How is your mood right now? </label>
		<input type="text" id="md" size="25" name="md" placeholder="Please type here." required>
		<br><br>
		<label for="cs">Is there sudden event in your life that causes you to have that kind of mood? </label>
		<input type="text" id="cs" size="25" name="cs" placeholder="Please type your experience here." required>
		<br><br>
		<label for="dcd">What made you decide to find immediate support? </label>
		<input type="text" id="dcd" size="25" name="dcd" placeholder="Please type your experience here." required>
		<input class="surbutton" id="btnSubmit" type="submit" value="Submit" name="submit">
		<br>
		</fieldset>
		</form>
		<br>
		<div class="surdiv">
		<table class="surveytab" id="surveyTable">
			{% for item in newPatient.survey_set.all %}
			<tr>
				<td>{{forloop.counter}}.</td>
				<td>Experience depression from {{item.sncwhen}}. Mood at this day ({{item.dttoday}})-{{item.md}} because of {{item.cs}}. Reason for immediate support {{item.dcd}}. <a href="/tolsys/edit/{{ newPatient.id }}">Edit</a> <a href="/tolsys/{{ newPatient.id }}/delete">Delete</a></td>
			</tr>
			{% endfor %}
		</table>
		<form action="/tolsys/{{newPatient.id}}/addappointment">
			<input class="surbutton" id="btnAppointment" type="submit" value="Next" name="submit">
		</form>
		<div>
	{% endblock %}